import cv2
import numpy as np
img = cv2.imread('redpoint3.jpg')
img2=cv2.imread('redpoint3.jpg')
red=np.uint8([[[0,0,255]]])
redhsv=cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
high_red = np.array([5,255,255])
low_red = np.array([-5,100,100])
# hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
mask = cv2.inRange(hsv, low_red, high_red)
kernel= np.ones((5,5),np.uint8)
mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
laplacian = cv2.Laplacian(mask,cv2.CV_64F)
# cv2.imshow('img',img)
a,contours, hierarchy = cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
if len(contours)!=0:
    cnt = contours[0]
    # hull = cv2.convexHull(cnt)
    epsilon = 0.009 * cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)
    cv2.drawContours(img, contours, -1, (255,255,0), 3)
    cv2.drawContours(img2, [approx], -1, (0,255,255), 3)
    cv2.imshow('img',img)
    cv2.imshow('img2',img2)
print(len(contours))
cv2.waitKey()
