import cv2
import numpy as np
img=cv2.imread('red.jpg')
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
bule_low=np.array([100,50,50])
bule_high=np.array([130,255,255])
mask=cv2.inRange(hsv,bule_low,bule_high)
res=cv2.bitwise_and(img,img,mask=mask)
kernel=np.ones((10,10),np.uint8)
mask1=cv2.erode(mask,kernel,iterations=1)
mask2 = cv2.dilate(mask1,kernel,iterations = 1)
# mask5=cv2.erode(mask4,kernel,iterations=1)
res2=cv2.bitwise_and(img,img,mask=mask1)
cv2.imshow('frame',img)
# cv2.imshow('mask',mask)
cv2.imshow('res',res)
# cv2.imshow('mask2',mask2)
cv2.imshow('res2',res2)
cv2.waitKey()
cv2.destroyAllWindows()